### ISSUE TITLE
On session expiration show "Login" button on OP page directly which should re-initiate login process (instead of "Go back" button)

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#1024]
## Describe the issue
Currently if session is expired we show screen with "Go back" button.

![screenshot 2](https://user-images.githubusercontent.com/6104200/45759795-5fb64400-bc31-11e8-8b02-16b19a06e94d.png)

Will request to avoid "Go back" button and instead have "Login" button. It should save end-user from clicking "Go back" and then "Login" again (as it is with support.gluu.org right now. It's not the case with oxtrust because it automatically redirects to OP if user is not login).

## Expected behavior
We should have "Login" button directly on OP page, which should allow to re-login (without going back to RP). 

## Actual behavior
User have to click "Go back" button and then "Login" on RP side to re-initiate authentication.

**Comment by yuriyz** [comment]
https://github.com/GluuFederation/oxAuth/issues/875

**Comment by yurem** [comment]
In oxAuth there is option to redirect to RP with error in JSON as payload. It's `errorHandlingMethod`: internal/remote.
Is it secure approach to do re-authentication after login session timeout? AuthZ request contains `state` parameter which also can be treated as short lived token.

**Comment by nynymike** [comment]
I don't see why it would be insecure to redirect to the login page. Is there some specific concern you have? I think redirecting to the login page would be more intuitive.

**Comment by yurem** [comment]
@nynymike do you mean OP or RP login page? Now when `errorHandlingMethod: remote` OP redirects to RP to allow trigger new AuthZ request.
For OP case it's not clear how this can help us? We have property `sessionIdUnauthenticatedUnusedLifetime` with default value 3 minute (OP start counting 3 minute again after each user iteration with OP). Admin can specify here another time range if needed and to allow login during bigger period of time.

As far as I understand the idea of this issue is to re-show login form on OP side on `sessionIdUnauthenticatedUnusedLifetime` timeout. But this will break login flow and trigger it re-initialization.

I think it's better to control behavior via `sessionIdUnauthenticatedUnusedLifetime` than adding one more workarounds.

`sessionIdUnauthenticatedUnusedLifetime` and `errorHandlingMethod` together can handle many use cases.

I mean one possible security issue. For my point of view AuthZ parameter `state` can be expired shorter (for security reasons) than OP will return response. This can led to login error.

**Comment by nynymike** [comment]
ok, I agree. I wonder how long Google sets this timeout by default.

**Comment by yurem** [comment]
Good question. Once we will implement [this](https://github.com/GluuFederation/oxCore/issues/115) we can return back to this question. This should help us to store data like unauthenticated sessions in another place. And as result we can hold unauthenticated sessions longer (without main functionality slowdown), even use RP session lifetime.

**Comment by yuriyz** [comment]
We can introduce `last_original=<request uri to authorization endpoint>` cookie that never expires. For given browser session it will be always overwritten with last call to Authorization Endpoint. When session is expired OP can still redirect to Authorization Endpoint with original request. Indeed `state` expiration is still valid. Advantage that we can avoid storing unauthenticated sessions on OP side.

Also it should address `bookmark` idea from @willow9886 .

**Comment by yuriyz** [comment]
Re: `bookmark` idea, as Will informed some users bookmarks login page (not authorization url) and expects that authorizations works correctly. Therefore here we want to save in cookie last authorization uri request and hit it if session is expired (instead of error).

**Comment by yuriyz** [comment]
@nynymike @yurem your thoughts on above are welcome.

**Comment by nynymike** [comment]
I'm closing this. Let's see if more users complain about it.
