### ISSUE TITLE
Multi value character attribute should be serialized as JSON array, not string

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxAuth#1056]
Attribute like ePSA are serialized as a JSON string, it should be array. Doesn't matter if this attribute has single value or multiple but we shouldn't serialize it as 'string'. 

Ref. ticket: https://support.gluu.org/single-sign-on/6963/gluu-oidc-does-not-serialize-multi-value-attributes-as-arrays-if-they-contain-only-a-single-element/

**Comment by yurem** [comment]
@qbert2k can you add reference to spec which we used to implement this?

**Comment by mzico** [comment]
@yurem @qbert2k : person who raised the issue saying it's a bug not enhancement.

**Comment by davidgvh** [comment]
Yes. The issue is that multi-valued attributes are being returned as strings if there is one item in the collection and as arrays otherwise. This means that two user profiles will serialize differently. With modern APIs internally handling serialization, this causes deserialization failures.

I discovered it when I added eduPersonScopedAffiliation to an OIDC scope and pulled several users. Most of the users had a single affiliation (student), but some had multiple affiliations (student, employee).

Whatever is returned needs to be consistent. Since they are multi-valued, they should be consistently serialized as arrays.

Am I correct in assuming that the Multivalued field on the GluuAttribute type is for identifying the schema for situations in which the values themselves are ambiguous?
