### ISSUE TITLE
oxAuth error message ( Error Encountered, An unexpected error has... ) improvement

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxAuth#1059]
Consider the following scenario: 

A login attempt fails or some other error occurs in a manner such that gluu redirects to the error page that says "Error Encountered, An unexpected error has occured at `2019-mm-dd hh:mm:ss PM/AM` and then shows the error message: "failed to authenticate". 

Can you modify the error handling such that if it's an exception or just an ERROR level message thrown on the backend, a `guid` is a part of that logged message and carried forward to be displayed on the error page? 

This would help to significantly speed up the error identification and diagnosis process.

**Comment by miltonbo** [comment]
Ok, based on the comments here and considering that this ticket was reported many months ago, I tried to reproduce a case when that issue would happend, however I haven't found the error, it's correct, that error page would be used in case of something really strange happend, unexpected error means that oxAuth had some `Exception`, like `NullPointerException` for example, in those cases it's correct, the page is going to the `/error.htm` page or doing a redirect to the RP depending on the configuration.

For failed authentication, I tried to do many cases, however always is showing the same result:
![image](https://user-images.githubusercontent.com/32613743/85204573-6761bb80-b2e3-11ea-808d-2b58391ff067.png)

Based on the chat that I had with @mzico, he refered that we could show the exception in the UI, however I think that could be a potential vulnerability, since it's highly recommended don't show system errors to the end user.

In this case we don't have something to implement here, it would be really good to reproduce that special case that was reported (if that was not already fixed in the new versions) and try to fix that unexpected error, to do that, it could be really good to have the steps to reproduce or the logs showing the error.

**Comment by miltonbo** [comment]
After chatting with @mzico we decided to close this issue.

**Comment by mtgluu** [comment]
I think some context was lost here. This request isn't necessarily for the failed to authenticate messaging. This was for scenarios where something happens that causes gluu to redirect to the error page that generically says "oops something happened". Imagine supporting a system with a million+ active daily users. Sometime some of them get that error page for whatever reason and then they email screenshots/copy paste the error into an email that makes its' way to a tech support team. There is no way in the current system for a support tech to troubleshoot that specific user's problem. 

That is the background context. Being able to provide a guid to a user in a failure scenario that provides a queryable value that can be passed to support/SRE to get related log data to see what *that* user was doing and exceptions logged for that specific user's interactions with the IDP for that session/usage occurance.

**Comment by bsirwaitis** [comment]
Request ticket re-open by end-user (Jeff Corrigan - Idemia).

**Comment by mtgluu** [comment]
Example: (could be for login errors or system errors)
![login-error](https://user-images.githubusercontent.com/22753814/86826660-aa978a80-c056-11ea-8de5-f4361405660e.png)

**Comment by bsirwaitis** [comment]
Here are the story requirements:

1) As a user of a Gluu production environment, when I encounter an error in the log-in authentication process, I want to be given a plain verbose explanation of the error, with a unique event ID that does not describe include any specific error detail, so that I can deliver the ID to the system administrator for diagnosis and resolution of my error.

2) As a Gluu production environment administrator, I want to have the ability to look at detailed log of user errors, so that when the user contacts the admin, he/she can give the specific index stamp and I can reference that specific indexed record in the log, and detirmine the root cause of the user error.

**Comment by miltonbo** [comment]
Ok, now it's fairly clear what is the expected result, general unexpected error could happend in many situations, however I understand the goal about the identifier showed to the end-user and also used to find very fast all logs related to the issue. I'll be working on it. Thank you.

**Comment by martynaslawinska** [comment]
The issue has been moved to Janssen: https://github.com/JanssenProject/jans-auth-server/issues/60
