### ISSUE TITLE
"sub" claim setting from ldap attribute does not work

### ISSUE THREAD

**Issue by ecky-l** [GluuFederation/oxAuth#1067]
According to the documentation [here](https://gluu.org/docs/ce/3.1.4/admin-guide/openid-connect/#public-subject-identifier-type) it should be possible to set the ldap attribute which is set as the "sub" claim to the access token, when public subject identifier type is active for a client.

Changing the attribute to something else than "inum" does not work. It results in no "sub" claim to be propagated into the access token at all.

**Comment by willow9886** [comment]
@ecky-l we ask that the community create issues on our [support portal](https://support.gluu.org) because on support, we get more information about the deployment that can be used to create an issue. 

That's why when you open an issue, the first line says:

> Unless you are Gluu staff, please first review and open an issue on https://support.gluu.org before opening an issue here. Thanks!

We need exact details to reproduce and fix an issue:

- which version of gluu?
- which OS? 
- which version of OS?
