### ISSUE TITLE
Add Interception Script:  Post-Authn Authorize

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#1129]
After the browser has a session, if a person visits a website, the RP can obtain a code without the user having to authenticate or authorize. In some cases, it is desirable to insert custom business logic before granting the code or tokens from the authorization endpoint. For example, you may want to force re-authentication. Such a script would be enabled through oxAuth JSON properties, for example `enablePostAuthnAuthorizeScript`. 

Also, you can't rely on the consent script being executed, for example if the client is pre-authorized.

**Comment by yurem** [comment]
This issue explain same update: https://github.com/GluuFederation/oxAuth/issues/1174

**Comment by yuriyz** [comment]
Actually there is comment from Mike about closing. It's duplicate.

https://github.com/GluuFederation/oxAuth/issues/1174#issuecomment-622425404

**Comment by yuriyz** [comment]
I will take over it as suggested by Mike.

**Comment by yuriyz** [comment]
Implemented in 4.2. Docs updated. Script allows to force re-authentication and authorization. After script is added it has to be associated with client in order to run.
Sample script: https://github.com/GluuFederation/oxAuth/blob/master/Server/integrations/postauthn/postauthn.py

![image](https://user-images.githubusercontent.com/2013070/82802481-a426c800-9e87-11ea-85fd-31a4acb3c5b0.png)
