### ISSUE TITLE
Registered clients disappear one day after created regardless of client expiration value ?

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxAuth#1199]
I Used oxd 4 to register a client on Gluu CE 4.0 (debian 9 + opendj) …

The operation works fine but I noticed the OIDC client disappeared from LDAP unexpectedly the next day

I found that registering via oxd ended up with something like this:

![client_vanishes](https://user-images.githubusercontent.com/5444180/68708728-4faea180-0562-11ea-9821-9e244e1decaa.png)

I set expiration for this client to be 10 years (oxAuthClientSecretExpiresAt). But those `del` and `oxAuthExpiration` apparently provoked the client to vanish

Neither `del` nor `oxAuthExpiration` are set when a client is created via oxTrust UI

Is this a problem in client registration endpoint ? Can you reproduce ?

**Comment by yurem** [comment]
I've updated oxAuth/oxTrust to use new generic filed `oxAuthExpiration` instead of `oxAuthClientSecretExpiresAt`. Now Cleaner Process/oxAuth/oxTrust uses same filed and should work well. There is one oxTrust issue which led to save wrong expiration time value: https://github.com/GluuFederation/oxTrust/issues/1877
