### ISSUE TITLE
"sub" claim is absent from id_token and userinfo response when certain attributes are used as source for it

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxAuth#1200]
## Environment
gluu-server-4.0-centos7 (OpenDJ)

## Describe the issue
If "Subject Type" is set to "public" for an OIDC client, "sub" claim won't be returned in `id_token` and userinfo response for certain attributes used as source for it (configured via "openidSubAttribute" oxAuth property)

## Steps To Reproduce
Detailed report can be found in ticket  7675
Steps below assume you have an RP setup which, some way or another, allows to check on tokens and jwts exchanged during its flows.

1. Register a client using "code" flow in oxTrust; make sure its "Subject Type" is set to public
2. On "JSON configuration -> oxAuth" tab, change "openidSubAttribute" to "uid"
3. Start the flow and check composition of returned `id_token` and userinfo response

## Expected behavior
"sub" claim is always present in both `id_token` and userinfo response

## Actual behavior
"sub" claim is always present for case when "inum" or "mail" attributes are used as source for it, but is absent when "uid" or "memberof" attributes are used (possibly this list doesn't end with those two). Can't see any clues in `oxauth.log`

**Comment by miltonbo** [comment]
I reviewed the issue reported, so I have this conclusions:

When JSON Configuration has: “openidSubAttribute”:”inum” or “openidSubAttribute”:”memberOf”
- Pairwise and Public work fine, in both cases “sub” field has values. It is important to clarify that the name of a field is **memberOf**, not memberof

When JSON Configuration has: “openidSubAttribute”:”uid”
- Pairwise works fine, “sub” field has a value, because the ID is generated dinamically using some params in every call.

- Public: doesn’t work fine, “sub” field doesn’t have a value, because there is not custom attribute in User entity called “uid”.

I put a default value in the case when openidSubAttribute is not found in the list of attributes of User entity, normally it uses **"inum"** value.
