### ISSUE TITLE
Logout test observed because we don't show success logout message to the user

### ISSUE THREAD

**Issue by miltonbo** [GluuFederation/oxAuth#1272]
## Issue
Test is waiting for a confirmation message that logout was done successfully, but we are showing a general error with some description.

#### Current message that we show:
![image](https://user-images.githubusercontent.com/32613743/75488554-f179c300-5986-11ea-9cbe-42e0dd10e04a.png)

#### This is an example of the expected message:
![image](https://user-images.githubusercontent.com/32613743/75488507-da3ad580-5986-11ea-9871-a451718e5053.png)

I identified this difference, but the final word will have OpenID foundation when they will have to review all of our screenshots, so I openned this issue to check if it is possible to have some confirmation message and if this one should be implemented or not.

**Comment by miltonbo** [comment]
#### Test url: 
https://op.certification.openid.net:62152/test_info/OP-RpInitLogout-No-params

#### Url used:
https://jenkins-ldap.gluu.org/oxauth/restv1/end_session?

**Comment by yuriyz** [comment]
@miltonbo if goal is to get successful logout without `post_logout_redirect_uri` then set `allowPostLogoutRedirectWithoutValidation=true`. As result AS will skip validation and will return front-channel HTML. Error above is because we force validation by default. Also you can customize HTML if needed via script: https://github.com/GluuFederation/docs-ce-prod/commit/d3e2745a8b08e84bc09e5ef7664d5a694d3aedd0
