### ISSUE TITLE
Support OpenID Connect prompt=select_account Authn request

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#1290]
As we may want to keep more then one session cookie in the web browser, and create a way for the user to switch between accounts.

```
session-1: c691e83d-eb1b-41f0-b453-fab905681b5b
session-2: 0ca6282f-943a-4f82-b7d0-0a752b0333b4
session-3: de510ab6-b06c-4393-86d8-12a7c501aafe
current_session: session1
```

To switch accounts, then redirect to the authorization endpoint with `prompt=select_account`,which is defined as a SHOULD in the OpenID Connect core spec. Using the `display=popup` param would also make sense here.

After which, the OP can return a form or popup with the active sessions, and allow the user to select the right account. 

After selecting the right account, the current_session cookie should be updated.

https://support.gluu.org/authentication/8113/oidc-flow-for-multiple-account-authentication-for-a-single-user/#at57902

**Comment by yuriyz** [comment]
Since we have heavy use of `session_id` I propose to implement it as :
```
session_id: de510ab6-b06c-4393-86d8-12a7c501aafe
current_sessions: ["c691e83d-eb1b-41f0-b453-fab905681b5b", "0ca6282f-943a-4f82-b7d0-0a752b0333b4", "de510ab6-b06c-4393-86d8-12a7c501aafe"]
```

Detailed use case : 
1. User is NOT logged in, it hits Authorization Endpoint
2. AS returns login form, user is logged in as `Account 1` and session created
```
session_id: de510ab6-b06c-4393-86d8-12a7c501aafe
current_sessions: ["de510ab6-b06c-4393-86d8-12a7c501aafe"]
```
3. User hits Authorization Endpoint with `prompt=select_account`. 
4. AS shows page where is listed `Account 1`. Page should contain button `Login with another account`.
5. User hits `Login with another account`
6. AS redirects to login page and on login adds new `Account 2` and sets new value for current `session_id`
```
session_id: c691e83d-eb1b-41f0-b453-fab905681b5b
current_sessions: ["de510ab6-b06c-4393-86d8-12a7c501aafe", "c691e83d-eb1b-41f0-b453-fab905681b5b"]
```
7. User hits Authorization Endpoint with `prompt=select_account`. 
AS shows: "Account 1", "Account 2"

**Comment by nynymike** [comment]
Looks good to me.

**Comment by yuriyz** [comment]
![image](https://user-images.githubusercontent.com/2013070/78658737-3ae8f680-78d3-11ea-8730-66dd7d258745.png)

**Comment by yuriyz** [comment]
Docs added here https://gluu.org/docs/gluu-server/4.2/admin-guide/session/#select-account
