### ISSUE TITLE
Add Java Requirements for Twilio

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#132]
See [Twilio Instructions for Java](https://www.twilio.com/docs/java/install) 

add to `pom.xml`
```xml
    <dependency>
        <groupId>com.twilio.sdk</groupId>
        <artifactId>twilio-java-sdk</artifactId>
        <version>5.8.0</version>
    </dependency>
```

**Comment by yurem** [comment]
I've updated pom.xml
But I specify to not include into final war this library by default.

If someone is planning to include it into oxauth.war he can run:
mvn -U -Dmaven.test.skip=true -Dtwilio-enabled clean package

I think we should not include 3rd party libraries into oxauth.war by default. This should minimize risk of bugs caused by these libraries. I've remember wikid client which override system trust store setting. As result oxAuth stop working properly after enabling this person authentication method...

Also we specify here: http://www.gluu.org/docs/articles/auth-script/#adding-libraries that they can put library into: /opt/tomcat/endorsed
Yes this should work. Bu I offer to put these 3rd party libraries into:
/opt/tomcat/lib.

As far as I remember endorsed folder should be used only for specific cases when we need to override system java packages. In other cases we should just add library we need to put it into lib folder.

**Comment by yurem** [comment]
Added supported auth scripts libraries by default
