### ISSUE TITLE
Remove sub from Userinfo response for password grant clients

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#1325]
There is no point to a pairwise `sub` claim for clients using the password grant. The client already has a username, which can be correlated. Just return the username as the sub value.

**Comment by uprightech** [comment]
@nynymike  , can we close this too ?

**Comment by yuriyz** [comment]
Code in user info is a bit outdated, `sub` value construction is centralized in `grant.getSub()`. Corrected it in https://github.com/GluuFederation/oxAuth/commit/5d9b11bb7ec9867853fba260f15fc5da424730f3

Closing ticket.
@uprightech PR instead of direct commit would be better so we can catch such kind of improvements in first place.

**Comment by uprightech** [comment]
Sorry , my bad , I realized I commited to the main repo instead of a PR.
