### ISSUE TITLE
There is no automatic expiration of UMA permissions/pct/rpt/etc with Couchbase

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#1528]
We need to set TTL on UMA entries which Couchbase should expire automatically

**Comment by yuriyz** [comment]
@yurem `oxUmaResourcePermission` has ttl set (with `@Expiration`). Is it something on ORM layer ?

https://github.com/GluuFederation/oxAuth/blob/bcaef50f3e6562ec7b651b74db8e6cbefde4f796/Model/src/main/java/org/gluu/oxauth/model/uma/persistence/UmaPermission.java#L50

**Comment by yuriyz** [comment]
We have checked it and with 4.2.3/4.2.2 `oxUmaResourcePermission` all newly created documents has TTL set under CB. `oxAuthUmaPCT` and `oxAuthUmaRPT` has it set since 4.3.0. If there are `oxUmaResourcePermission` documents which are created prior to 4.2.3/4.2.2 then they may not have TTL set. It should be removed manually.
