### ISSUE TITLE
CIBA feat: add custom script method to get device registration token.

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#1537]
## Describe the issue
During device registration, token is saved into `oxAuthBackchannelDeviceRegistrationToken` attribute of the user entity. During backchannel authorization AS expects device registration token in `oxAuthBackchannelDeviceRegistrationToken` attribute.

Request is to add custom script method to get device registration token.

**Comment by nynymike** [comment]
Is this really the request? Or is it just to add an oxAuth JSON property to enable another attribute other then `oxAuthBackchannelDeviceRegistrationToken` to be specified?

**Comment by yuriyz** [comment]
From comments: `the device ID is already in the user's inum`.

It seems there are cases when we need script to extract device id from user's inum.

**Comment by yuriyz** [comment]
Actually I agree, we should add configuration property to allow change hard-coded `oxAuthBackchannelDeviceRegistrationToken`.

Encoding device ID into user's inum looks like corner case. It's not clear how it should work if new device registration occurs. We should prefer dedicated attribute.

**Comment by Milton-Ch** [comment]
Hi, not sure what is the requirement here, however some context, for CIBA we could have two options to notify end user:
1. Via Firebase push notification, in this case `oxAuthBackchannelDeviceRegistrationToken` is used to say Firebase send it to this device, in this flow we cannot modify that value, Firebase generates it during device registration.
2. Via custom script, in this case, device registration token could be what ever the client device wants, since they would be sending his custom value and when AS has to notify to the end user, AS only picks up this value and send it to the custom script already added, responsability of sending the notification remains in the script itself.

`oxAuthBackchannelDeviceRegistrationToken` is only for internal usage, RS shouldn't know anything about it.

**Comment by yuriyz** [comment]
Agreed. It comes from support ticket 9626, maybe you can comment on it too so we have it in history.

**Comment by Milton-Ch** [comment]
This ticket is still pending for some answer from client, it might require or not changes, I answered client concerns in support ticket, presented a couple of options to handle what customer wants, til now seems that we shouldn't require any code change, but let see what client says.

**Comment by Milton-Ch** [comment]
Closing this ticket because support ticket was closed after I gave a couple of options to the client and we didn't get any answer.
