### ISSUE TITLE
Don't show expired refresh token info in logs

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxAuth#1539]
Ref ticket: https://support.gluu.org/other/9619/search-persistence-errors-are-spewing-in-the-logs/

According to customer, we don't need to log info of expired token in oxauth log for long. Is there any way to improve this logging?

**Comment by yuriyz** [comment]
AS has no idea whether its expired or whether its invalid token. In both cases for AS it's invalid.

For example:
1) RP gets refresh_token1
2) RP requests token with refresh_token1 -> SUCCESS
3) RP requests token with refresh_token1 -> FAILURE

At step 3) we have no idea whether step 2) occurred or not. What if RP send refresh_token_fake ?

From AS point of view refresh_token1 or refresh_token_fake are both invalid tokens and thus it’s errors.

AS has no way to track all tokens that was present before (because they are already removed).

**Comment by zaphod72** [comment]
The main problem is that this is logged at ERROR level.
Many software departments, including ours, require that ERRORs are fixed.
If this is expected behavior it should not be logging as an ERROR.
