### ISSUE TITLE
feat(oxauth): support wildcard character in redirect_uri 

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxAuth#1918]
## Description

As was discussed before with @yuriyz , a customer asked if it's possible to add wildcard character support when they specify redirect_uri-s for their OIDC clients.

According to [the spec](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest),

>This URI MUST exactly match one of the Redirection URI values for the Client pre-registered at the OpenID Provider, with the matching performed as described in Section 6.2.1 of [[RFC3986]](https://openid.net/specs/openid-connect-core-1_0.html#RFC3986) (Simple String Comparison).

..so it may seem like it's not allowed. But it seems that some other OP implementations decide to add it as an optional feature anyway - so may worth consideration.

**Comment by yuriyz** [comment]
In general we should not recomment wildcard usage in redirect_uri due to security. However if really needed support is added in 4.5.6 and backported to 4.2.3.sp2.

Wildcard can be enabled via new `"allowWildcardRedirectUri": true` AS configuration property.
During client registration redirect uri will be validated against `clientWhiteList`. `"clientWhiteList": ["*"]` allows everything. In general it makes sense to narrow it with something like `"clientWhiteList": ["*.mydomain.com"]`. Which will allow redirect uris like: `*.mydomain.com`, `*.mydomain.com/path`.

4.2.3.sp2 war with wildcard support:
https://jenkins.gluu.org/maven/org/gluu/oxauth-server/4.2.3.sp2/oxauth-server-4.2.3.sp2.war
