### ISSUE TITLE
Migration to Weld 3.0.0.CR2

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#221]
After migration to Seam 2.3.1.Final we need to think about next step.
The easier update is to migrate to weld 2.3.4.Final.

We need to investigate this and do migration if it's easy to do.

**Comment by yuriyz** [comment]
One more option is to move to Spring. It will be harder to move to Spring then to Weld. But lets compare pros&cons. We can even move to pure Guice and add lib by lib that are really required instead of heavy tools. I propose to have small table of proposals and compare pros&cons each of the method before final decision.

**Comment by yurem** [comment]
I vote for solution which easy to implement. Also current oxauth.war size is 50Mb. Hence Seam 2.3.1 is not very heavy.

**Comment by yurem** [comment]
After research I decided to orient on Weld 3.0.0.CR2. It's works without problem under Jetty 9.3.16.*

**Comment by yurem** [comment]
Implemeented.
