### ISSUE TITLE
prompt=login leads to double authentication of the user

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#249]
1. Hit authorization endpoint
https://ce-dev2.gluu.org/oxauth/authorize?scope=openid+profile+email+address+clientinfo+mobile_phone+phone&response_type=code&nonce=n-0S6_WzA2Mj&redirect_uri=https%3A%2F%2Fgluu.loc%2Fwp-login.php%3Foption%3DoxdOpenId&state=af0ifjsldkj&client_id=%40%2140EA.D454.9D4F.E876%210001%21ECE8.BBEF%210008%216097.3FDC&acr_values=basic&prompt=login
2. Login
3. Consent page is shown. Please click "Allow"
Result: Login page is shown again. If login again only then user is redirected. 
Expected result: user is redirected directly after click on "Allow"

**Comment by nynymike** [comment]
Javier, can you prioritize this bug?

**Comment by qbert2k** [comment]
Hello Yuriy,

The right Authorization Endpoint URL is:
https://ce-dev2.gluu.org/oxauth/seam/resource/restv1/oxauth/authorize
See: https://ce-dev2.gluu.org/.well-known/openid-configuration

Instead of:
https://ce-dev2.gluu.org/oxauth/authorize
because it is not the Autorization Endpoint, it is the authorize page (with the allow button).

For example:

https://ce-dev2.gluu.org/oxauth/seam/resource/restv1/oxauth/authorize?scope=openid+profile+email+address+clientinfo+mobile_phone+phone&response_type=code&nonce=n-0S6_WzA2Mj&redirect_uri=https%3A%2F%2Fclient.example.com%2Fcb&state=af0ifjsldkj&client_id=%40!40EA.D454.9D4F.E876!0001!ECE8.BBEF!0008!FA5A.0AA0&acr_values=basic&prompt=login

**Comment by yuriyz** [comment]
@qbert2k right, authorization endpoint redirects you to login and after successful login to authorization page. Why is it redirect back to login after user is clicking "Allow" on authorization page? Did you test it with prompt=login?
