### ISSUE TITLE
`&nonce=nonce` mandatory in OpenID Connect authorization code flow   

### ISSUE THREAD

**Issue by zamilskhan** [GluuFederation/oxAuth#316]
The `nonce` parameter is given to be `optional` in the Authorization Code Flow. It is mandatory now according to [this ticket](https://support.gluu.org/installation/getting-missing-required-parameter-when-trying-to-use-oxauth-rp-as-outlined-in-the-documentation-3125/). The [relative openID specification](http://openid.net/specs/openid-connect-core-1_0.html#AuthRequest) is linked here.

**Comment by aliaksander-samuseu** [comment]
@yuriyz , OIDC spec reads explicitly that in code flow the "nonce" parameter is optional, and in implicit flow it's required. But it's not perfectly clear how it is for hybrid flows. As Zamil noted, core spec's section on hybrid flow references [this section](http://openid.net/specs/openid-connect-core-1_0.html#AuthRequest) (it's related to code flow) telling everything there applies, except for "response_type" parameter for which it provides its own requirements. In that case "nonce" must be optional for hybrid flow.

But as request in this ticket shows, unless "nonce" is added to request url, oxauth tells it isn't correct. I tested it for myself and for "response_type=code+id_token" (hybrid flow), unless you provide "nonce" too, it's rejected because of "incorrect parameter".

Could you provide your opinion what is expected behavior here?

**Comment by yuriyz** [comment]
@aliaksander-samuseu @zamilskhan there different hybrid flows. But general rule should be 

```
if response_type contains id_token then nonce is required because it must be included into ID token to avoid replay attack
```

If your hybrid flow contains id_token value in response_type then nonce is required otherwise it is optional.

**Comment by zamilskhan** [comment]
@yuriyz thank you
