### ISSUE TITLE
SAML Script enhancement

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxAuth#361]
Target: Dynamically modify user information in asimba server ldap. If new attribute is released from remote IDP, add that attribute with values here in asimba server's ldap. 

Here are couple of points from latest testing: 
- No information of user 'tahmid' is available in asimba server ldap. 
- First SSO performed. 
- Here is the information of this user in asimba server ldap. 
  ![firstattempt](https://cloud.githubusercontent.com/assets/7156097/19775315/a50d6a56-9c35-11e6-86d6-60dcdc68bc2b.png)
- Released FirstName/givenName from 'nest.gluu.org' ( remote authentication server )
- Second SSO performed
- Here is the screenshot of this user in asimba server ldap from second attempt ( check... there is no indication of new attribute here 'givenName' ).  
  ![secondattempt](https://cloud.githubusercontent.com/assets/7156097/19775317/a82cbdb8-9c35-11e6-91fa-79a7a3627c58.png)
- Removed this user's information from asimba server ldap
- Third SSO performed
- Here is the screenshot of this user in asimba server ldap from third attempt ( check.. now 'givenName' is added ). 
  ![final_and_target](https://cloud.githubusercontent.com/assets/7156097/19775322/ad0775ee-9c35-11e6-897d-4afe905a44c9.png)

And this is our target actually. We should 'dynamically' add any new attribute in user's information.

**Comment by happymcplaksin** [comment]
Zico has perfectly described what we're after. For what it's worth this is how we assumed SAML Script would work when it was first described to us.

Also, we **definitely** have a need for this because folks are in-progress adding required attributes to their Remote IDPs. So we know we will have some SAML-Script-created users that will later show up with new attributes and we need the new attributes in Asimba server LDAP.

Thank you!

**Comment by yurem** [comment]
I updated script and added new property:
saml_update_user: true

Can you check if it working as expected now?

**Comment by yurem** [comment]
Fixed
