### ISSUE TITLE
Add setAmrValues method interface to custom authentication script

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#38]
Perhaps we can define in oxAuth a way for the admin to set what gets returned as amr.
AMR is a list of strings, returned by the OP, to provide more information about the authentication that happened. No one knows what the company may want to return for amr--values are out of scope of OpenID Connect. For example, one could imagine amr's returned such as ['10', 'https://example.com/acr/duo', 'silver']

The best way to handle this is to enable the company to set the amr values in the interception script. We should add a method ``'def setAmrValues(self, amrValuesList):`` where amrValues is a python list.

**Comment by yurem** [comment]
What is purpose of this extra method? Should it just return list of synonymous of specific interceptor script?

**Comment by nynymike** [comment]
`amr` is defined in the id_token http://openid.net/specs/openid-connect-core-1_0.html#IDToken 

However, there is no way currently in the Gluu Server to set the value of `amr`

In fact, there is no way to know what should even be returned for `amr`, which is why I am proposing that it can be set in the custom authentication script. 

It should default to nothing, but optionally, it can be set by the admin.

**Comment by yurem** [comment]
I've tested how it works now.
For example, if we pass amr_values=basic in authorization request oxAuth returns id_token which contains amr=basic claim/

Hence currently we uses interceptor script name in all places.
If we need to change amr/amr_value we only need to change interceptor script name.
Also we can add new mandatory person interceptor script property to allow admin set other amr value than interceptor script name.

**Comment by yuriyz** [comment]
Since our authentication following interception script the name of the script is totally enough as amr value unless we plan to keep logic of authentication inside the script.

For example if we have "duo" for duo and "u2f" for u2f then name of the script keeps whole needed information. But if we create script that dynamically decide what authentication method to use, e.g. "dynamic" which will choose authentication based on some other parameters (duo or u2f) then we have to inject amr values inside that script. 

Do we plan to use such "dynamic" interception scripts? If yes then we need to inject those amr values inside script. If no, then issue can be closed since name of the scripts is enough and fits Connect concept ("Parties using this claim will need to agree upon the meanings of the values used, which may be context-specific.").

Thoughts?

**Comment by yurem** [comment]
Mike, can you explain your idea with 'def setAmrValues(self, amrValuesList):' method?

I think new method in interceptor script will led to many clones of the same script which make support and upgrade more complex.

**Comment by nynymike** [comment]
Actually the name of the script is returned as the acr. amr_values is an array of strings. This is used to return extra information to the client. We have no idea what should be returned here--the only answer is to let the organization define the values. For example, they may return something like this ['US', '232', 'red'] ... corresponding to some internal information... like I said, they can return whatever they like in amr.

**Comment by yurem** [comment]
I think it's fixed already. @nynymike Wthat do you think?
