### ISSUE TITLE
Configure User Claims present in id_token

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#423]
OpenID Connect allows user claims to be passed in the id_token, but there is no way in the Gluu Server to configure which user claims or scopes should be passed in the id_token. Futhermore, this may need to be configured on a per-client basis.

**Comment by worm333** [comment]
Do I understand correctly that before #340 all claims were incorporated into id_token and this issue is aimed to give admins the opportunity to decide what particular claims should/shouldn't be included into id_token?

**Comment by worm333** [comment]
I've added "Include Claims In Id Token" field to /identity/client/manage/update/{client_id} page. The field is disabled if legacyIdTokenClaims property (from AppConfiguration) is false.

If legacyIdTokenClaims is true and "Include Claims In Id Token" field is checked, then all claims from requested scopes are included in Id Token (for this client).

**Comment by yurem** [comment]
@worm333 your pull request contains code to enable passing claims to id_token for specific client. But it now allows to do:

``
but there is no way in the Gluu Server to configure which user claims or scopes should be passed in the id_token. 
``

We need to implement this too according to this issue requirements

**Comment by worm333** [comment]
@yurem you're right. However, we discussed this issue with Mike and agreed that for CE 3.1.0 would be sufficient to make legacyIDToken setting per client, instead of global.

So, right now we do not provide the possibility to select particular claims that would be included in id_token, instead we allow gluu admins to choose for which particular client all the claims wiil be included or not.

**Comment by yurem** [comment]
ok, It makes sense. Thank you for explanation
