### ISSUE TITLE
Implement better HTTP Header Security

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#437]
I was just reading this article: https://blog.appcanary.com/2017/http-security-headers.html

* Google gets an **A-** https://accounts.https://observatory.mozilla.org/analyze.html?host=accounts.google.com

* Gluu gets a **D+** https://observatory.mozilla.org/analyze.html?host=idp.gluu.org

Can we do a little better?

**Comment by ganesh-at-wiw** [comment]
https://github.com/GluuFederation/community-edition-setup/commit/f3cbc1bef62f5ed7522a270665650e30738ab42f#diff-03977dfe18120f823fed2a0408021ef1

Above link contains my work on apache headers.

@yurem please have a look at content security policy.

**Comment by happymcplaksin** [comment]
Thanks for working on this! Many vendors are *not* working on this sort of thing so I really appreciate Gluu being proactive!

**Comment by yurem** [comment]
After adding few headers and update scripts in oxTrust we get <B>B+</B> rating: https://observatory.mozilla.org/analyze.html?host=ce-dev3.gluu.org

I'm changing Milestone to CE 3.1.0 to continue work on this in next version to achieve <A>A</A> rating.

**Comment by yurem** [comment]
To apply more security settings we need to do small research and split this issue by few smaller issues. I think so, because some setting requires code changes. without code updates we can get functionality issue due to added restrictions. We need to check each option as separate issue. And it's better to start work on such issue during starting work on new release. I'm moving it to 3.2.0..

**Comment by nynymike** [comment]
Closing this because it's an issue for web server.
