### ISSUE TITLE
Customization in 3.1.x

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#501]
After migration from Seam to Weld we can't use page.xml files because it's part of Seam.

In 3.1.0 oxAuth we found out how to replace all parts of page.xml functionality.

1. To call bean on rendering page and pass request parameters we can use JSF 2.2 functionality:

	<f:metadata>
		<f:viewAction action="#{authenticator.prepareAuthenticationForStep}"
			if="#{sessionStateService.notSessionStateAuthenticated}" />

		<f:viewParam name="login_hint" value="#{loginAction.loginHint}" />
	</f:metadata>

2. For url rewrite we uses ocpsoft [prettyfaces](http://www.ocpsoft.org/prettyfaces/). We can try to replace it with [rewrite](https://github.com/ocpsoft/rewrite/tree/master/integration-cdi) library which has CDI integration.

3. To support navigation rules we also uses JSF 2.2. We added rules to faces-config.xml.

Now we need to re-enable customizations in 3.1.x. The problematic points are 2 and 3. Now we use per app files faces-config.xml and pretty-config.xml We need to find solution how to allow to use them on page level. For example:
- page1.xhtml
- page1.faces.xml
- page.pretty.xml

Hence we need somehow tell JSF 2.2 and pretty faces (or just rewrite) to use these files too. I think it's possible because JSF 2.2 supports faces.xml files. But it uses them only in [flows](https://github.com/jsflive/jsf22-examples/tree/master/jsf22-flows). We need to do the same without flows.
URL rewrite library also supports runtime configurations..

Moreover to avoid adding 2 files per page we can add *.pretty.xml tags into *.faces.xml

Let me know if you have any questions.

**Comment by worm333** [comment]
I was looking at JSF docs regarding using multiple faces-config.xml files. Actually there are two ways how to do this:
1. Create context initialization parameter named `javax.faces.CONFIG_FILES` with comma separated webcontent-relative paths to all external files.

2. Create multiple jar files in classpath with META-INF/faces-config.xml file inside. Then on startup JSF application will load all the faces-config.xml files from all jars.

First option is almost what we're looking for, except that we can not indicate faces-config.xml files dynamically, because all the external paths should be predefined.

In [this commit](https://github.com/GluuFederation/oxAuth/pull/514/commits/639756dfc20355916d3e6e82fd12b4f29f8027f9) I overrode some files from `com.sun.faces.config` package in order to read *.faces-config.xml files from `/opt/gluu/jetty/oxauth/custom/pages` directory. The rules are as follows:

1. all faces-config files in `/opt/gluu/jetty/oxauth/custom/pages` should match the pattern: `*.faces-config.xml`
2. all custom pages e.g. login2.xhtml should be placed in `/opt/gluu/jetty/oxauth/custom/pages`

Despite the fact that [this method](https://github.com/GluuFederation/oxAuth/pull/514/commits/639756dfc20355916d3e6e82fd12b4f29f8027f9) works, in the future we may have problems with updating jsf-impl-2.2.14.jar, since the implementation of overridden methods could change significantly.

**Comment by worm333** [comment]
Finally, url rewriting mechanism is done. I've created a custom implementation of HttpConfigurationProvider interface which completely replaced the need to use pretty-config.xml. The implementation works as follows: for each .xhtml file in `oxauth.war` and `${catalina.base}/custom/pages` adding [rewriting rules](http://www.ocpsoft.org/rewrite/examples/) , e.g.: `addRule(Join.path("/login").to("/login.htm"))`.

All the changes regarding this issue are in [this pull request](https://github.com/GluuFederation/oxAuth/pull/515).

**Comment by yurem** [comment]
I like your idea to automatically add all  rewrite rules for all JSF pages. But overwrite JSF configuration mechanize cause many question. It's hack which we need to update on each JSF library version update.

I think instead of this hack we need "[JSF 2.2 programmatic faces-config.xml](http://www.omnifaces-fans.org/2015/10/jsf-22-programmatic-faces-configxml.html)"

With this mechanism we can add our faces configuration to faces-config.xml from code.

Also I offer to not mix all navigation rules into one big faces-config.xml I believe one big file after some will contains garbage (unused rules) and periodically developers can faces with conflicts during commits. Seam page.xml files is easier to support than one big file.

Instead of page.xml we can introduce faces.xml. And our programmatic faces configuration (previous point) can add them via ApplicationConfigurationPopulator approach. Also in same way we can add customer faces.xml files.

**Comment by yurem** [comment]
And one last bonus idea:
```
<?xml version="1.0" encoding="UTF-8"?>
<faces-config xmlns="http://xmlns.jcp.org/xml/ns/javaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:pf="http://ocpsoft.org/schema/rewrite-config-prettyfaces"
	xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-facesconfig_2_2.xsd http://ocpsoft.org/schema/rewrite-config-prettyfaces http://ocpsoft.org/xml/ns/prettyfaces/rewrite-config-prettyfaces.xsd"
        version="2.2">

	<pf:url-mapping id="my_super_rule">
		<pf:pattern value="/admin_login" />
		<pf:view-id value="/hidden/login.htm" />
	</pf:url-mapping>

	<!-- /login.xhtml -->
	<navigation-rule>
		<from-view-id>/hidden/login.xhtml</from-view-id>
...
	</navigation-rule>
</faces-config>
```
It contains mix of JSF 2.2 and pretty faces rewrite rules.

ApplicationConfigurationPopulator can handle this. It can add rewrite rules and faces configuration during startup up.

**Comment by worm333** [comment]
Ok, I found out an elegant way how to add navigation rules programmatically. Here is the final version of [ConfigureListener](https://github.com/GluuFederation/oxAuth/blob/11dc12ed5a1824babc731ae1eda7e0181f970ee5/Server/src/main/java/org/xdi/oxauth/customization/ConfigureListener.java) class.

But first things first: primarily I've tried to create faces-config.xml file as it shown in the following example: "[JSF 2.2 programmatic faces-config.xml](http://www.omnifaces-fans.org/2015/10/jsf-22-programmatic-faces-configxml.html)". I managed to create new faces-config programmatically, but I ran into a problem: default navigation rules were not overwritten by the customized ones.

Of course we can create all the faces-config files: default and customized ones programmatically, but we'll have a mess in one file. So I decided to go deeper into jsf implementation and came out with the [final solution](https://github.com/GluuFederation/oxAuth/pull/515). It's clean and light and does not break data encapsulation(no need it reflection).

Thus we can create default faces-configs the usual way: with xml and add customized navigation rules programmatically.
In [this commit](https://github.com/GluuFederation/oxAuth/pull/515/commits/11dc12ed5a1824babc731ae1eda7e0181f970ee5) I've also splited navigation rules into several files located in: `/WEB-INF/navigation/` directory.

**Comment by worm333** [comment]
I think I figured out how we can use `ApplicationConfigurationPopulator `, soon I'll prepare another solution in a separate pull request, so we can decide what solution is more properly fits for our needs.

**Comment by worm333** [comment]
New customization method is ready: #521. Both ways of customization: #521 and #515  are good, but I think the [last one](https://github.com/GluuFederation/oxAuth/pull/521) - indeed what we are looking for. How it works:
1. All default navigation files are moved to classpath directory: `META-INF/naviagation` and renamed to match pattern: `*.navigation.xml` (we don't want to tell JSF that these files are faces-configs, otherwise JSF will load and process them internally, this is what we try to avoid).
2. At start [FacesConfigPopulator](https://github.com/GluuFederation/oxAuth/blob/23c2c0e559c7ff3c36373588eb62cd508b02e07b/Server/src/main/java/org/xdi/oxauth/customization/FacesConfigPopulator.java) will load all files located in ${catalina.base}/custom/pages that matches the pattern: `*.navigation.xml` and merge them into new xml document. Afterwards all the default navigation files located in classpath:`META-INF/navigation` will be processed in the same way.

Thus there is no need to update web.xml each time, when we need to add new navigation file.

After merging one of the above pull requests we can move jsf related code outside of oxAuth into oxCore (I think it's better be done after merging).
