### ISSUE TITLE
Support FluentD logging

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#565]
Can we add jar file and log4j2 adapter for FluentD? This would provide another good option for cluster logging. 

https://github.com/wywygmbh/log4j-plugin-fluency

**Comment by worm333** [comment]
#601 , [this pull request](https://github.com/GluuFederation/oxTrust/pull/642) and [this commit](https://github.com/GluuFederation/community-edition-setup/commit/3a9de2d3d0e0b82ff01010977222a818a8632694) are related with this issue.

**Comment by worm333** [comment]
Here is the instruction how to integrate [FluentD](https://www.fluentd.org/) with [oxAuth](https://github.com/GluuFederation/oxAuth):

1. Update [log4j2.xml](https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/resources/log4j2.xml) by adding [FluencyAppender](https://github.com/wywygmbh/log4j-plugin-fluency/blob/master/src/com/wywy/log4j/appender/FluencyAppender.java):
```
        <Fluency name="fluency" tag="yourTag">
            <!-- all settings are optional, see defaultFluency() for default values -->
            <!-- you can add as may fields as you like (or none at all) -->
            <StaticField name="application">yourApplication</StaticField>
            <StaticField name="someOtherField">some value</StaticField>
            <Server host="primary-node" port="24224"/>
            <Server host="secondary-node" port="24224"/>
            <FluencyConfig
              ackResponseMode="true"
              fileBackupDir="/tmp/fluency"
              bufferChunkInitialSize="4194304"
              bufferChunkRetentionSize="16777216"
              maxBufferSize="268435456"
              waitUntilBufferFlushed="30"
              waitUntilFlusherTerminated="40"
              flushIntervalMillis="200"
              senderMaxRetryCount="12" />
        </Fluency>
```
The simplest configuration could be like this: `<Fluency name="fluency" tag="oxAuth_Fluency"/>`.
By default [FluencyAppender](https://github.com/wywygmbh/log4j-plugin-fluency/blob/master/src/com/wywy/log4j/appender/FluencyAppender.java) will connect to `127.0.0.1:24224 `.
More about Fluency configuration you can read [here](https://github.com/wywygmbh/log4j-plugin-fluency).


2. Update [FluentD]((https://www.fluentd.org/)) configuration file (e.g `/etc/td-agent/td-agent.conf`) by adding `yourTag`:
```
<match oxAuth_Fluency>
  @type stdout
</match>
```
More about configuring [FluentD](https://www.fluentd.org/) you can read [here](https://docs.fluentd.org/v0.12/articles/config-file).

3. Restart FluentD: 
```
/etc/init.d/td-agent stop
/etc/init.d/td-agent start
```
Restart oxAuth:
```
service oxauth restart
```

Logger also could be configured externally. In order to do this navigate to `/identity/logviewer/configure` and pass path to your log4j2 configuration file to the `oxAuth External log4j location` field. For example:

<img width="754" alt="screen shot 2017-08-04 at 5 58 25 pm" src="https://user-images.githubusercontent.com/5003491/28975875-5fb52150-7944-11e7-9d71-ac75ed5134ca.png">
