### ISSUE TITLE
No support for "popup" value of "display" request parameter, while we claim we support it in metadata

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxAuth#574]
Environment:
Ubuntu 14.04, gluu-server-3.0.2

Preconditions:
A working OIDC setup using your Gluu instance as OP

Steps to reproduce:
1. Add "&display=popup" to request from your RP using any method you prefer
2. Open page at `/.well-known/openid-configuration` at your instance and note contents of "display_values_supported" array there.

Result:
A regular oxAuth's login page is displayed. The array looks like this:
```
    "display_values_supported": [
        "page",
        "popup"
    ]
```

Expected result:
According to [OIDC spec](http://openid.net/specs/openid-connect-core-1_0.html):

> popup
> The Authorization Server SHOULD display the authentication and consent UI consistent with a popup User Agent window. The popup User Agent window should be of an appropriate size for a login-focused dialog and should not obscure the entire window that it is popping up over.

As we list it in metadata, it should be implemented as described.

**Comment by qbert2k** [comment]
I think it is not a bug because the RP is responsible for creating the popup, not the OP. And the OP is only responsible to display the UI consistently with the appropriate size for a popup dialog.

![screen shot 2017-11-06 at 3 43 57 pm](https://user-images.githubusercontent.com/2474616/32460496-5ddbef12-c309-11e7-903f-e40b4124aab7.png)
