### ISSUE TITLE
Why it is client secret is always required in token request Api?

### ISSUE THREAD

**Issue by arvindsinghtomar** [GluuFederation/oxAuth#590]
@qbert2k 
Why is client secret always required as header param in token end point even if I have kept "none" as the Authentication method for the Token Endpoint?
I am trying to use refresh token API in put android project but it always returns me unauthorized if client secret is not passed as param.
I am calling Api at token end point (https://......../oxauth/seam/resource/restv1/oxauth/token)

**Comment by qbert2k** [comment]
The supported client authentication methods are: client_secret_basic, client_secret_post, client_secret_jwt, and private_key_jwt.

None is not supported. If you are using the Implicit Flow the refresh_token will not be issued.

**Comment by nynymike** [comment]
But PKCE uses code flow but no secret...

**Comment by worm333** [comment]
At first I was confused because `/oxauth/restv1/token` does not require any header parameter, all the parameters should be sent in the request body.

However looking into [TokenRestWebService](https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/java/org/xdi/oxauth/token/ws/rs/TokenRestWebService.java#L89) and [TokenRestWebServiceImpl](https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/java/org/xdi/oxauth/token/ws/rs/TokenRestWebServiceImpl.java#L90) I've noticed that `client_secret` is an optional parameter and moreover it's never used in the code. This confused me even more, probably we should delete it (from [TokenRestWebService](https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/java/org/xdi/oxauth/token/ws/rs/TokenRestWebService.java#L89) and  [TokenRestWebServiceImpl](https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/java/org/xdi/oxauth/token/ws/rs/TokenRestWebServiceImpl.java#L90)).

`401 (Unauthorized) status code` is raised from [AuthenticationFilter](https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/java/org/xdi/oxauth/auth/AuthenticationFilter.java#L311). In [this pull request](https://github.com/GluuFederation/oxAuth/pull/595) I've added the following condition: if client's authentication method is set to `none`, then `client_secret` is not required.

Example request:
```
curl -k -H "Content-Type: application/x-www-form-urlencoded" -X POST --data 'client_id=@!A8DE.1C81.2EC6.9B20!0001!826A.437B!0008!3010.E1B0.1465.824D&grant_type=client_credentials' https://gluu.localhost.info/oxauth/restv1/token
```
Example response:
```
{"access_token":"f5be84ea-1dc0-450b-92ff-fc8c13bc8f13","token_type":"bearer","expires_in":9999}
```
