### ISSUE TITLE
Client-specific refresh token expiration 

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#603]
Need to enable a client configuration option to enable the management of refresh token intervals. For example, some clients may need a shorter refresh token expiration.

**Comment by worm333** [comment]
Added the necessary changes in the following pull requests: [oxTrust](https://github.com/GluuFederation/oxTrust/pull/646), [oxAuth](https://github.com/GluuFederation/oxAuth/pull/605) and [community_edition_setup](https://github.com/GluuFederation/community-edition-setup/pull/320).

**Comment by worm333** [comment]
Little explanation on the modifications above. In [AppConfiguration](https://github.com/GluuFederation/oxAuth/blob/master/Model/src/main/java/org/xdi/oxauth/model/configuration/AppConfiguration.java) we already have [refreshTokenLifetime](https://github.com/GluuFederation/oxAuth/blob/master/Model/src/main/java/org/xdi/oxauth/model/configuration/AppConfiguration.java#L83) field, which was used as a refresh token expiration value for all clients.

I decided to not remove  [refreshTokenLifetime](https://github.com/GluuFederation/oxAuth/blob/master/Model/src/main/java/org/xdi/oxauth/model/configuration/AppConfiguration.java#L83) field because of the following case:

- when "client-specific refresh token" is not set (is empty or null), the value from [refreshTokenLifetime](https://github.com/GluuFederation/oxAuth/blob/master/Model/src/main/java/org/xdi/oxauth/model/configuration/AppConfiguration.java#L83) will be set as a refresh token expiration.
