### ISSUE TITLE
U2F Authentication not working

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#613]
Error page is displayed as soon as I switched to U2F authentication. I see this in the script log:

```
2017-08-13 22:53:04,155 WARN  [qtp2008017533-15] [org.xdi.oxauth.service.external.ExternalAuthenticationService] (ExternalAuthenticationService.java:332) - Current acr_values: 'u2f' isn't valid
```

**Comment by yurem** [comment]
This message oxAuth shows only if script method:
```
    def isValidAuthenticationMethod(self, usageType, configurationAttributes):
        return True
```

Returns False. In this script in setup this [method](https://github.com/GluuFederation/community-edition-setup/blob/master/static/extension/person_authentication/U2fExternalAuthenticator.py) always return True. Maybe you not waited 30 seconds to give oxAuth to reload script.

U2F works fine for me since beta2.

**Comment by yurem** [comment]
It's marked as working fine in QA board
