### ISSUE TITLE
Invalid "scopes" field in Dynamic Client Registration request and response

### ISSUE THREAD

**Issue by bahadorraha** [GluuFederation/oxAuth#700]
Hi,
I was unable to dynamically register a client to oxAuth authorization server. Through some debugging I found that oxAuth returns a "scopes" value of type array, in its registration response, like this:

`"scopes": ["openid", "uma_protection", "permission"]`

whereas my client expects "scope" field (a string containing a space-separated list of scope values) instead, like this:

`"scope": "openid email profile"`

I also checked [OAuth 2.0 Dynamic Client Registration Protocol](https://tools.ietf.org/html/rfc7591#section-2), there is only **scope** value allowed not **scopes**!

**Comment by nynymike** [comment]
Javier any thoughts on this? I wouldn't want to break anyone's code. So if we decide to change this, then we should make an oxAuth property that specifies if the scopes come back as array or string.  The value should be array if the property is not present. But going forward string should be the default.

**Comment by qbert2k** [comment]
OAuth Dynamic Client Registration spec was created some time after OpenID Connect Dynamic Client Registration and we were based in OIC spec. That's because the “scopes” param was added as a custom param as JSON array of string.

Following the RFC7591 for OAuth 2.0 Dynamic Registration oxAuth now supports request and response of param "scope" as a string containing a space-separated list of scope values.

Also to do not break anyone code oxAuth is still supporting the request and response param "scopes" but it is marked as @deprecated to be removed in later versions.

There is a new configuration parameter to select the desired param format:

- To use param "scopes" JSON String List:
```
"legacyDynamicRegistrationScopeParam": true
```

- To use param "scope" space-separated String List
```
"legacyDynamicRegistrationScopeParam": false
```

**Comment by qbert2k** [comment]
Also I have added a new issue to add support for new parameter for Dynamic Client Registration: Add support for Client metadata: software_id, software_version, software_statement #704
