### ISSUE TITLE
Persist Client Authorizations

### ISSUE THREAD

**Issue by pfeliprada** [GluuFederation/oxAuth#773]
Hi I posted in Gluu forums about an issue regarding Persist Client Authorizations and I was advised by Michael to bring it here. Here is the link referring to my post in Gluu https://support.gluu.org/single-sign-on/5281/persist-client-authorizations/.  

I would like to persist my users before proceeding to the "main page" which is the page I put in my Redirect Login URI. I can do this by setting the Persist Client Authorizations field to true and it is working well. The thing is when I click the allow button I get redirected to my "main page" which is fine but when I click the don't allow button ~~i get redirected to the Post Logout Redirect URI~~ then if I access my website again the session is not ended and I continue to get the "Persist Client Authorization" prompt page so if I click don't allow again the cycle keeps on repeating. I tried to handle it by code but I can't force to log out the user since there is no issued id_token. 

I would like to propose that once the user click the "Don't Allow" button the user will be redirected to the Post Logout Redirect URI ~~(which is currently implemented)~~ with the session already ended so that if the user would access the website the user will be forced to log in again and will not be prompted with the "Persist Client Authorization" prompt page. 

THANKS! Hoping for your positive feedbacks.

**Comment by pfeliprada** [comment]
**UPDATES**

Correction: It does not redirect to the post logout redirect URI instead it proceeds to the "main page" followed with this error in the url: error=access_denied&error_description=The+resource+owner+or+authorization+server+denied+the+request.&state=1elzooc#

**Comment by pfeliprada** [comment]
**UPDATES**

Hi I would also like to ask is the "Persist Client Authorizations" page can be localized based on our language? lets say French language. I tried to change my language to Russian but the "Persist Client Authorizations" page is still english.

THANKS AGAIN!

**Comment by nynymike** [comment]
agreed

**Comment by pfeliprada** [comment]
Thank you!

**Comment by qbert2k** [comment]
See ticket: https://support.gluu.org/single-sign-on/5281/persist-client-authorizations/

**Comment by qbert2k** [comment]
Regarding first comment, yes, if the authorization request is valid (all params including redirection URI) and the user authenticates but the user decides to do not grant authorization by clicking the button Do not allow, then the right response is to be redirected to the redirection URI with the error parameter access_denied. In a subsequent authorization request the user will be prompted for authorization directly because he/she is already authenticated.

>>If the resource owner denies the access request or if the request
   fails for reasons other than a missing or invalid redirection URI,
   the authorization server informs the client by adding the following
   parameters to the query component of the redirection URI using the
   "application/x-www-form-urlencoded" format, per Appendix B:

Please review https://tools.ietf.org/html/rfc6749#section-4.1.2.1

------

Regarding second comment, I have opened a new issue to debug ui_locales param. oxAuth #867

https://github.com/GluuFederation/oxAuth/issues/867
