### ISSUE TITLE
Import clients with existing client_ids

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#782]
If an organizations already has existing OAuth clients, and these need to be imported, there should be a way. See [5246](https://support.gluu.org/5246) and [4310](https://support.gluu.org/single-sign-on/4310/how-to-customize-client_id/)

**Comment by mtgluu** [comment]
Ticket 5246 referenced above is not visible. It puts a red banner at the top of the page:
"You are not authorized to view this ticket. If you think this is a mistake, please email support@gluu.org."

**Comment by willow9886** [comment]
Yep, private tickets visible to gluu staff and customer named contact only.

**Comment by mtgluu** [comment]
Ah OK. I assume 5246 is related to the export from the existing system? I can't see that tkt but I had to do the same thing recently which is why I this github ticket was interesting. It was a pretty clean process to export from one system and import into the other. 

The noteworthy items after importing to the new system:

I did have to reset the pwd so it was encrypted using the keys on the new gluu server. Otherwise clientauth blew an exception "[org.xdi.oxauth.service.ClientService] (ClientService.java:109) - javax.crypto.BadPaddingException: Given final block not properly padded". The "convert_client.py" file referenced in 4310 above looks like it addresses this issue. 

The allowed scopes(dynamic) on the clientconfig also needed to be readded in the UI. This was because the oxAuthScope dn that links the two together was no longer the same after import into the new gluu ldap system.  The convert_client.py doesn't really address that issue but it one of those steps that's worth doing a manual comparison of after setup to verify they match.

**Comment by afroDC** [comment]
@qbert2k adding an arbitrary inum to a client is possible as long as you add the `@!` to the beginning of the name. For example:

![screenshot from 2018-08-15 13-27-34](https://user-images.githubusercontent.com/30447907/44165692-06398300-a08f-11e8-8eae-105492b1b6d6.png)

oxauth.log:
```
2018-08-15 18:14:13,724 INFO  [qtp1190524793-25] [org.xdi.oxauth.auth.Authenticator] (Authenticator.java:217) - Authentication success for Client: '@!test-arbitrary'
2018-08-15 18:19:54,313 INFO  [qtp1190524793-26] [org.xdi.oxauth.auth.Authenticator] (Authenticator.java:217) - Authentication success for Client: '@!test-arbitrary'
```

Without the prefix of `@!` the client will fail with the following errors:

oxauth.log:
```
2018-08-15 17:44:00,103 INFO  [qtp1190524793-26] [org.xdi.oxauth.auth.Authenticator] (Authenticator.java:427) - Authentication failed for User: 'test-arbitrary'
2018-08-15 17:44:00,104 INFO  [qtp1190524793-26] [org.xdi.oxauth.auth.Authenticator] (Authenticator.java:164) - Authentication failed for 'test-arbitrary'
```

my client:

```
response indicates failure, status=401, body={"error":"invalid_client","error_description":"Client authentication failed (e.g. unknown client, no client authentication included, or unsupported authentication method). The authorization server MAY return an HTTP 401 (Unauthorized) status code to indicate which HTTP authentication schemes are supported. If the client attempted to authenticate via the Authorization request header field, the authorization server MUST respond with an HTTP 401 (Unauthorized) status code, and include the WWW-Authenticate response header field matching the authentication scheme used by the client."}
```

Is there any reason that the oxauth code hard-codes the `@!` identifier for clients already identified as such under `ou=clients,o=<inum>!0001!<org>,o=gluu`. Ideally the code should read any client_id/inum under that dn as such, and not a user, as my error seems to be showing.

**Comment by yuriyz** [comment]
I'm trying to validate this ticket but I can't find in docs how actually we can import clients with existing ids. Also I don't see it in referenced commits. Re-opening it.

**Comment by yurem** [comment]
Moved to 3.1.5 after discussion with @afroDC and @willow9886

**Comment by afroDC** [comment]
@yuriyz to import existing clients would take some data munging to format it to fit the current requirements of Gluu Server. I'm not sure it would be an easy and direct 1:1 conversion as the data could vary from IDP to IDP.

**Comment by yuriyz** [comment]
I see, moving it to 4.0.

**Comment by yuriyz** [comment]
https://github.com/GluuFederation/oxAuth/issues/823

**Comment by nynymike** [comment]
Let's see if any customers raise this issue again. I'm not sure it's a problem in 4.x
