### ISSUE TITLE
pairwiseIdentifiers branch does not appear when using persistent strategy

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxAuth#783]
Using 3.1.3 RC4 (centos 6)

When setting the oxAuth JSON property for pairwisetype to "persistent"

![persistent](https://user-images.githubusercontent.com/3717101/34447064-1233edb4-eca6-11e7-88f3-2deded622813.png)

The sub-tree under the person entry: `ou=pairwiseIdentifiers,inum=(person-inum),ou=people,o=(org-inum),o=gluu` does not appear when logging in to applications.

**Comment by yurem** [comment]
Why it should persist algorithmic identifiers? According to the code there is no random part in it. Hence this [method](https://github.com/GluuFederation/oxAuth/blob/08f9e4cf379aca47becf4ef769722849def47e48/Server/src/main/java/org/xdi/oxauth/service/PairwiseIdentifierService.java#L84) looks like regenerate same identifier.

**Comment by nynymike** [comment]
If you don't persist the pairwise id, it will not be searchable. In some cases, we need to remember which ppid is associated with a person. Also, if the client_ids in the sector_identifier_uris change, it may change the ppid?

**Comment by yurem** [comment]
We already persist in LDAP `persistent` pairwise Id. This ID is GUID. And it's easy to use it in search, etc.. Also it's not dependents on any keys, client inum, etc... It's associated with specific hostname only.

`algorithmic` is the HMACSHA256 signature. Since it's byte based signature it's not very useful to use it in search. Also it's easy to change it. Admin just need to change pairwiseCalculationKey/pairwiseCalculationSalt in oxAuth config. Why in this case we need to persist this type of pairwise id? Maybe in new versions we will decide to rotate these keys on daily basic.

From my point there is generic part here with Saml. In Saml we also have PersistentId, TransientId, RandomId. And only first one is persistent.

**Comment by yurem** [comment]
@jgomer2001 to enable `pairwise:persistent` you should do:

1. Enable `persistent` pairwise id type in oxAuth JSON config.
2. In client specify `Subject Type: pairwise`
