### ISSUE TITLE
CleanupTimer has to run in own connection pool to not effect oxauth performance

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#813]
Background are described in this support ticket.
https://support.gluu.org/access-management/5456/uma-ticket-cleanup-strategy-in-ldap/

**Comment by yuriyz** [comment]
We have to unify objects that can be cleaned up. Clean up itself can be performed by oxauth or by external application/script (scheduled by cron).

Object that is deletable by cleaner should have :
* `oxAuthExpiration` - date when object should be considered as expired (the number of milliseconds since January 1, 1970, 00:00:00 GMT)
* `oxDeletable` - boolean flag true/false. If false clean up job should not delete the object.

Filter should look as:
`&(oxAuthExpiration<=now)(oxDeletable=true))`.

By default oxauth clean timer is turned on however it should be possible to turn it off (for cases when we wish to process it by external script or node in clustered environment).
* cleanServiceEnabled - boolean attribute with true value by default.
* cleanServiceInterval - clean up service interval.

Clean service should run queries with separate connection pool.

TODO:

- check all clean service code and identify objects that does not use `oxAuthExpiration` attribute
- make all clean up code work via `oxAuthExpiration` 
- add `oxDeletable` and update filters.
- check how it should work with couchbase.

**Comment by nynymike** [comment]
I like it!

**Comment by yurem** [comment]
I like idea described in second comment. This should improve performance. I only don't understand subject. Maybe we need to update it? How separate pool can help with this? Cleaner is synchronous process. Hence it do all types object clean up in turn. In each iteration it uses just one connection. Maybe instead of using new connection pool which oxAuth should maintain we can allow to specify priority of cleaner thread to reduce this process priority.

**Comment by corriganjeff** [comment]
> I like idea described in second comment. This should improve performance. I only don't understand subject. Maybe we need to update it? How separate pool can help with this? Cleaner is synchronous process. Hence it do all types object clean up in turn. In each iteration it uses just one connection. Maybe instead of using new connection pool which oxAuth should maintain we can allow to specify priority of cleaner thread to reduce this process priority.

Yuri, It's been a while since I tested this so I don't recall the specific details. IIRC the reason for the split connection pool is because if the system is already under load, when the cleanup job starts up it seemed like it was grabbing whatever connections were available (not just a single connection). Each connection was only used to query/delete 100 records. Meanwhile there was service refusal and/or errors for users attempting to login, for clients attempting to get idtokens/userinfo and for new user registrations/updates over scim. Putting these cleanup services into their own connection pool, independent from gluu's operating pool would resolve this. It might also be worthwhile to increase the size as well. On a system with consistent use, 100 tickets/query takes quite a while to cleanup.

**Comment by yurem** [comment]
Maybe the issue is in high load and cleaner process priority might help?
Exhaustive answer on question about connections we can get after next files analysis:
`/opt/gluu/jetty/oxauth/logs/oxauth_persistence_ldap_statistics.log`
`/opt/gluu/jetty/identity/logs/oxtrust_persistence_ldap_statistics.log` (SCIM opeartions)

The connection pool helps to reduce CPU time needed for connection creation. If it has enough connections specified in configuration it should work well. Maybe instead of splitting connection pool you can use separate server server for clean up? In this case we need to find out how to limit where to run clean up.

**Comment by yuriyz** [comment]
started new doc page for clean up https://github.com/GluuFederation/docs-ce-prod/blob/4.0/docs/source/operation/cleanup.md

**Comment by yuriyz** [comment]
Before proceeding with clean up ticket we have to drop grant objects from persistance. Opened ticket here https://github.com/GluuFederation/oxAuth/issues/1033

**Comment by yuriyz** [comment]
#1033 is done, resuming work on this ticket.

**Comment by yuriyz** [comment]
done in master. Opened separate ticket on oxTrust to make new configuration properties editable https://github.com/GluuFederation/oxTrust/issues/1576
