### ISSUE TITLE
Review the prepareForStep method of passport social script

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxAuth#816]
# Description
 Currently the method prepareForStep of passport script seems useless.

That method is https://github.com/GluuFederation/oxAuth/blob/version_3.1.4/Server/integrations/passport/PassportExternalAuthenticator.py#L277

1. It return true even in case of error
1. The execution of that method always throw an exception on the third line after the try catch block
1. Removing the try catch block of that method, the passport social works Well

**Comment by jgomer2001** [comment]
You are right, that `prepareForStep` is trying to do a flow similar to [saml](https://gluu.org/docs/ce/authn-guide/inbound-saml-passport/#sequence-diagram) one

but the social should be like [this](https://github.com/GluuFederation/gluu-passport#sequence-diagram), which is actually implemented doing web browser redirects (for instance see function `idp_redirect` in `passportlogin.xhtml`). That's why it works despite the script crashes.

I added [this](https://github.com/GluuFederation/gluu-passport/issues/38) issue as an attempt to rework the flow and consolidate saml/social into a single script if possible.
