### ISSUE TITLE
uma /rpt/status endpoint isn't working well?

### ISSUE THREAD

**Issue by dejwsz** [GluuFederation/oxAuth#82]
Hi,
just wonder if uma /rpt/status works well. I can put anything as token parameter - not only valid rpt and it always responses with 200 OK status and it always displays details like this:
{"active":false,"exp":null,"iat":null,"nbf":null,"permissions":null,"client_id":null,"sub":null,"aud":null,"iss":null,"jti":null}. I think this is a bug or something? For my surprise it concerns stable edition 2.3.4.

**Comment by dejwsz** [comment]
I have to sorry, my request was malformed and token parameter was improperly passed. This endpoint work very well. The only thing which is not fully OK is that it responses with 200 OK for every wrong token data it gets. I think it shouldn't be like that. Apart from this if proper RPT is passed it responses with JSON with RPT details as it should be.

**Comment by yuriyz** [comment]
@dejwsz implementation was made according to oauth introspection introduced by Richer.
https://tools.ietf.org/html/draft-richer-oauth-introspection-06#page-3

Snippet from specification (page 4)
```
 Following is a non-normative example response to an inactive or
   invalid token (with line wraps for display purposes only):

   HTTP/1.1 200 OK
   Content-Type: application/json
   Cache-Control: no-store

   {
    "active": false
   }
```
I'm closing this issue as invalid, since implementation is made according to specification (response is always OK but if token is invalid then "active" is false).
