### ISSUE TITLE
Provide errors with exact explanation what is wrong.

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#855]
We need to improve error messages on oxauth. I believe bad examples are in specs directly. Sample from spec:
```
{
   "error":"invalid_request",
   "description": "The request is missing a required parameter, includes an unsupported parameter or parameter value, or is otherwise malformed."
}
```
Is parameter missing? What exactly parameter is missing? Or maybe all are present but some are not supported? Or it is malformed? It is too generic. From beginning we followed spec examples and as for errors it looks very bad. So indeed lets think how to better improve it.

I propose in description provide exact reason. Like
```
{
   "error":"invalid_request",
   "description":"redirect_uri parameter is missed."
}
```
Otherwise if we want to keep it very close to specs examples then we can add "reason" json key:
```
{
   "error":"invalid_request",
   "description": "The request is missing a required parameter, includes an unsupported parameter or parameter value, or is otherwise malformed.",
   "reason":"redirect_uri parameter is missed."
}
```

**Comment by qbert2k** [comment]
I like option B adding a reason key in json response.

**Comment by mtgluu** [comment]
I like the reason key as well. One overall comment....It is nice that the current message makes penetration testing a little bit harder. 

For example, if you send a bad clientid you get back the current generic message "The request is missing a required parameter, includes an unsupported parameter or parameter value, or is otherwise malformed.". The same message applies if you use a good clientID with an unregistered redirect uri. 

Leaving some ambiguity in the external messaging in this case isn't a bad thing.

**Comment by yuriyz** [comment]
It seems we all like option with `reason`, lets proceed with it.

**Comment by yuriyz** [comment]
TODO:

- make sure we always return exact reason for `invalid_client_metadata`.

**Comment by yuriyz** [comment]
Most of the errors now have additional `reason` field in error response that provides exact reason of the failure. Some errors are not covered since it requires major code refactoring which is unwanted because it may effect stability (e.g. inner ifs in Authorization Endpoint). We should improve it during other features development and refactor major flow handling. For now considering it as solved.
