### ISSUE TITLE
Values for javax.faces.converter.XXX strings in messages.properties not overriding default messages

### ISSUE THREAD

**Issue by guyaparker** [GluuFederation/oxAuth#895]
In the messages.properties file there are strings defined that are intended to over ride the default values JSF  conversion and validation error messages:

> javax.faces.converter.BigDecimalConverter.DECIMAL
> 
> ...
> 
> javax.faces.validator.LongRangeValidator.TYPE

These appear to not be used because if I have (say) an integer where JSF rejects the non-integer value being set the error message shown is in the format of the default message:

> javax.faces.converter.IntegerConverter.INTEGER={2}: ''{0}'' must be a number consisting of one or more digits.

When it should be in the format defined in messages.properties:

> javax.faces.converter.IntegerConverter.INTEGER=value must be an integer

The solution is that faces-config.xml requires the following in order to over ride the default values:

```
<message-bundle>
    messages
</message-bundle>
```

See:
https://stackoverflow.com/questions/2668161/internationalization-in-jsf-when-to-use-message-bundle-and-resource-bundle

https://support.gluu.org/customization/5980/values-for-javaxfacesconverterxxx-strings-in-messagesproperties-not-overriding-default-messages/

**Comment by yurem** [comment]
There is prototype of java extension which will be part of 4.2.

Here is the [code](https://github.com/GluuFederation/oxCore/tree/master/core-java-ext). You can download it from [here](https://ox.gluu.org/maven/org/gluu/oxcore-java-ext/4.2.0-SNAPSHOT/oxcore-java-ext-4.2.0-SNAPSHOT.jar).

To enable it you need to do:
1. put this library into `/opt/jre/jre/lib/ext`.
2. Check if inside `faces-config.xml` there is no `<message-bundle>` since we expects to use default `javax.faces.Messages.properties` bundle name.
3.  Create new folder and put into `/opt/gluu/jetty/oxauth/custom/i18n/javax/faces` it Messages.* from `oxauth.war!/javax.faces-2.3.9.jar!/javax/faces/Messages.properties`
4.  Restart oxauth service
