### ISSUE TITLE
Support JWT token algs PS256, PS384, PS512

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#997]

**Comment by qbert2k** [comment]
Some notes to consider:

1. The new signature algorithms PS256, PS384, PS512 are ready to use and are published in the configuration endpoint: userinfo_signing_alg_values_supported, id_token_signing_alg_values_supported, request_object_signing_alg_values_supported, token_endpoint_auth_signing_alg_values_supported.

2. I have generated a new JWKS for client and server to test with Jenkins at ce-dev3.gluu.org

3. CE setup and oxTrust were updated.

4. oxEleven was not updated because SoftHSM is not working with the new algs.
